services:

  broker:
    build: .
    command: python Broker.py
    ports:
      - "5555:5555"
      - "5556:5556"

  proxy:
    build: .
    command: python Proxy.py
    ports:
      - "5557:5557"
      - "5558:5558"

  reference:
    build: .
    command: python ReferenceServer_sync.py
    ports:
      - "6000:6000"

  servidor-1:
    build: .
    hostname: servidor-1
    container_name: servidor-1
    command: python Servidor_sync.py
    depends_on:
      - broker
      - proxy
      - reference

  servidor-2:
    build: .
    hostname: servidor-2
    container_name: servidor-2
    command: python Servidor_sync.py
    depends_on:
      - broker
      - proxy
      - reference

  cliente:
    build: .
    command: python Cliente.py
    depends_on:
      - servidor-1
      - servidor-2
    deploy:
      replicas: 3